### ISSUE TITLE
intellij IDEA CE 2020.3 not support

### ISSUE THREAD

**Issue by Lcccocoa** [cjamcu/getx-snippets-intelliJ#3]
In intellij IDEA CE 2020.3 Plugins market not found the plugin， maybe not support 2020.3

**Comment by xuanswe** [comment]
Same here, I couldn't find the plugin.

IntelliJ IDEA 2020.3 (Ultimate Edition)
Build #IU-203.5981.155, built on November 30, 2020
Runtime version: 11.0.9+11-b1145.21 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0

**Comment by cjamcu** [comment]
@Lcccocoa @nguyenxndaidev Please, you can try to install the extension again and tell me if it works. Thank you

**Comment by Lcccocoa** [comment]
Great! Solved!

**Comment by Lcccocoa** [comment]
Great! Solved!

**Comment by xuanswe** [comment]
Found plugin! Thanks!
