### ISSUE TITLE
Not Working with IntelliJ IDEA 2020.3.1

### ISSUE THREAD

**Issue by SmarterVision** [cjamcu/getx-snippets-intelliJ#7]
Would you please check the plugin with the last release of IntelliJ 2020.3.1

```
IntelliJ IDEA 2020.3.1 (Ultimate Edition)
Build #IU-203.6682.168, built on December 29, 2020
```

**Comment by cjamcu** [comment]
@SmarterVision Please, you can try to install the extension again and tell me if it works. Thank you
